#if !canImport(ObjectiveC)
import XCTest

extension Bip39Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Bip39Tests = [
        ("testEntropyToMnemonic", testEntropyToMnemonic),
        ("testInvalidMnemonic", testInvalidMnemonic),
        ("testMnemonicToEntropy", testMnemonicToEntropy),
        ("testSeed", testSeed),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(Bip39Tests.__allTests__Bip39Tests),
    ]
}
#endif
